name: build-json

on:
  schedule:
    - cron: "0 6 * * *"    # täglich 06:00 UTC
  workflow_dispatch:       # manuell startbar

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "Branch: $GITHUB_REF"
          ls -la
          ls -la scripts || true
          ls -la data || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python info
        run: |
          python -V
          pip -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 openai
          fi

      - name: Build JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/build_json.py
        continue-on-error: true

      - name: Fallback if build failed
        run: |
          if [ ! -f data/latest.json ]; then
            echo "No data/latest.json produced – writing fallback."
            python - <<'PY'
import os, json
from datetime import datetime, timezone
os.makedirs("data", exist_ok=True)
with open("data/latest.json", "w", encoding="utf-8") as f:
    json.dump({
        "company":"Pernod Ricard",
        "generated_at": datetime.now(timezone.utc).strftime("%Y-_
