name: build-json

on:
  schedule:
    - cron: "0 6 * * *"   # täglich 06:00 UTC
  workflow_dispatch:      # manuell startbar

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/build_json.py

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
