name: build-json

on:
  schedule:
    - cron: '0 6 * * *'   # täglich 06:00 UTC
  workflow_dispatch:      # manueller Start möglich

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "Branch: $GITHUB_REF"
          ls -la
          ls -la scripts || true
          ls -la data || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 openai
          fi

      - name: Build JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python pernod_ricard_agent_repo_full/scripts/build_json.py || true # Wichtig: Pfad anpassen, falls deine Datei NICHT hier liegt
          python scripts/build_json.py
        continue-on-error: true

      - name: Fallback if no output
        run: |
          if [ ! -f data/latest.json ]; then
            echo "No data/latest.json produced – writing fallback."
            mkdir -p data
            printf '%s' '{\n  "company": "Pernod Ricard",\n  "generated_at": "1970-01-01T00:00:00Z",\n  "signals": [],\n  "sources": []\n}\n' > data/latest.json
          fi

      - name: Show output
        run: |
          wc -c data/latest.json
          head -n 40 data/latest.json

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
